development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:23b5a4c9d9d16434cf3133724da702df@crestfish.redistogo.com:10053/
  channel_prefix: PediChat_production
